### ISSUE TITLE
bart nufft fails on large dataset (Assertion `index >= 0' failed)

### ISSUE THREAD

**Issue by dabosch** [mrirecon/bart#342] opened 2024-10-28 15:11 UTC
Hi,

I have a somewhat large dataset. While a reduced version can be worked with using nufft, I get errors with the full data.
I tried some debugging myself but am at my wit's end (I just don't understand the BART source well enough...)

```bash
> bart show -m "rufis_08.seq"
Type: complex float
Dimensions: 16
AoD:    3       19692864        1       1       1       1       1       1       1       1       1       1       1       1       1       1
> bart show -m "rufis_08.dat"
Type: complex float
Dimensions: 16
AoD:    1       19692864        1       10      1       1       1       1       1       1       1       1       1       1       1       1
> bart nufft   -i -d4 "rufis_08.seq" "rufis_08.dat" "rufis_08.nufft"
bart: /opt/src/bart/src/noncart/grid.c:134: intlookup: Assertion `index >= 0' failed.
```

In order to look for the error I tried inserting a few debug statements into the `grid.c` file:
```C
#define DEBUG(...) printf("%d: %s = %d\n", __LINE__, #__VA_ARGS__, __VA_ARGS__)
#define DEBUGf(...) printf("%d: %s = %f\n",__LINE__, #__VA_ARGS__, __VA_ARGS__)
```

in `intlookup()`, right before the assert statement:
```C
if (index < 0){DEBUG(n);DEBUGf(x);DEBUG(index);}
```

in `grid_point_gen()` right before the call to `intlookup`:
```C
// test for nan
float ww = frac/width;
if (ww != ww) {DEBUGf(ww); DEBUGf(width); DEBUGf(frac);DEBUG(w);DEBUGf(pos[N]);}
```

The output I then get shows some indices went wrong:

```
WARN: BART version v0.9.00-601-g5554d1c-dirty is not reproducible.
523: ww = nan
523: width = 3.000000
523: frac = nan
523: w = -2147483648
523: pos[N] = -nan
138: n = 1000
138: x = nan
138: index = -2147483648
bart: /opt/src/bart/src/noncart/grid.c:139: intlookup: Assertion `index >= 0' failed.

```

If it is of interest, the files I use can be found here: https://owncloud.tuebingen.mpg.de/index.php/s/8Pemab4ApTjyJms

BTW: when using the cuda-version, I do not get an error message, but the resulting file only contains nan values. Since I do not know much about CUDA I didn't even try to debug this.

Best,
Dario

**Comment by mblum94** [comment] 2024-12-03 14:27
Hi Dario,

I'd like to try to reproduce the bug, but it appears that the owncloud share is deleted. Would it be possible that you reupload the data?

Best,
Moritz

**Comment by dabosch** [comment] 2024-12-04 07:17
Hi Moritz,

here's the data again:
https://owncloud.tuebingen.mpg.de/index.php/s/akm7fqz9mSNAXDq

Thanks for looking into this!

Best,
Dario

**Comment by mblum94** [comment] 2024-12-04 22:28
Hi Dario,

I think the problem is that your trajectory file contains NANs in position 19692506 (zero based indexing).
How do you generate the trajectory?

I'll close the issue, but I'm happy to reopen if the issue persists.

Best,
Moritz

**Closed by mblum94** 2024-12-04 22:28 UTC
